# Generated by Django 4.2.1 on 2023-07-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctordb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Doctor_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=200, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('Expertise_Field', models.TextField(blank=True, max_length=200, null=True)),
                ('Doc_Image', models.ImageField(blank=True, null=True, upload_to='Doctor')),
            ],
        ),
    ]
